---
- name: Install pip
  apt: name=python-pip state=present

- name: Install pexpect using pip
  pip: name=pexpect

- name: Install ufw
  apt: name=ufw state=present

- name: Enable firewall
  expect:
    command: ufw enable
    responses:
      y : "y"

- name: Allow ssh
  # become: yes
  # become_method: sudo
  command: ufw allow ssh

- name: Replace with IPV6=yes
  lineinfile:
    dest: /etc/default/ufw
    regexp: ^IPV6=
    line: IPV6=yes

- name: Disable firewall
  # become: yes
  # become_method: sudo
  command: ufw disable

- name: Enable firewall
  expect:
    command: ufw enable
    responses:
      y : "y"

- name: Deny incoming requests
  # become: yes
  # become_method: sudo
  command: ufw default deny incoming

- name: Allow outgoing requests
  # become: yes
  # become_method: sudo
  command: ufw default allow outgoing
